### ISSUE TITLE
Wrong battery capacity?

### ISSUE THREAD

**Issue by sboukortt** [sonyxperiadev/device-sony-apollo#18]
Hi,

`power_profile.xml` states that the battery’s capacity is 2760mAh:
https://github.com/sonyxperiadev/device-sony-apollo/blob/db920e459c6f746e270dd06b78f06b60819908a5/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135

But according to [the phone’s specifications](https://www.sonymobile.com/global-en/products/phones/xperia-xz2-compact/specifications/), it should be 2870.

**Comment by MartinX3** [comment]
Same for the XZ2 in
https://github.com/sonyxperiadev/device-sony-akari/blob/master/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135
according to
https://www.sonymobile.com/global-en/products/phones/xperia-xz2/specifications/

and the XZ3
https://github.com/sonyxperiadev/device-sony-akatsuki/blob/master/overlay/frameworks/base/core/res/res/xml/power_profile.xml#L135
https://www.sonymobile.com/global-en/products/phones/xperia-xz3/specifications/

And @sboukortt please reopen it in the official bug tracker repo.

**Comment by MartinX3** [comment]
https://github.com/sonyxperiadev/device-sony-akatsuki/pull/15
https://github.com/sonyxperiadev/device-sony-akari/pull/17
https://github.com/sonyxperiadev/device-sony-apollo/pull/19
