### ISSUE TITLE
Where is kernel defconf?

### ISSUE THREAD

**Issue by mariogrip** [sonyxperiadev/device-sony-apollo#3]
I cannot seem to find the kernel config file aosp_tama_apollo_defconfig for this device? it is not in the cloned kernel repo https://github.com/sonyxperiadev/kernel/tree/aosp/LA.UM.6.3.r1/arch/arm64/configs

**Comment by bartcubbins** [comment]
Tama platform is not ready and has the wip status

**Comment by mirh** [comment]
https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/configs/aosp_tama_apollo_defconfig

**Comment by bartcubbins** [comment]
@jerpelea I assume it can be closed

**Comment by jerpelea** [comment]
please wait for the official announcement!
